plugins {
    alias(libs.plugins.shadow)
}

// Paper API 1.21.1 requires Java 21+
tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

repositories {
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'

    implementation project(':api')
    implementation project(':common:loader-utils')
}

processResources {
    filesMatching('plugin.yml') {
        expand 'pluginVersion': project.ext.fullVersion
    }
}

shadowJar {
    archiveFileName = "LuckPerms-Bukkit-${project.ext.fullVersion}.jar"

    from {
        project(':bukkit').tasks.shadowJar.archiveFile
    }

    manifest {
        attributes(["paperweight-mappings-namespace": "mojang"])
    }
}

artifacts {
    archives shadowJar
}
